//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TayaIT.Enterprise.EMadbatah.BLL.EPServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EPServiceClient.IEPService")]
    public interface IEPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPService/GetData", ReplyAction="http://tempuri.org/IEPService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPService/GetEParlimentSessionDetails", ReplyAction="http://tempuri.org/IEPService/GetEParlimentSessionDetailsResponse")]
        System.Data.DataSet GetEParlimentSessionDetails(long sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPService/UpdateEParlimentSessionDetails", ReplyAction="http://tempuri.org/IEPService/UpdateEParlimentSessionDetailsResponse")]
        System.Data.DataSet UpdateEParlimentSessionDetails(long sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPService/IngestContentsForFinalApprove", ReplyAction="http://tempuri.org/IEPService/IngestContentsForFinalApproveResponse")]
        bool IngestContentsForFinalApprove(long sessionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEPService/CheckHealth", ReplyAction="http://tempuri.org/IEPService/CheckHealthResponse")]
        int CheckHealth(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEPServiceChannel : TayaIT.Enterprise.EMadbatah.BLL.EPServiceClient.IEPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EPServiceClient : System.ServiceModel.ClientBase<TayaIT.Enterprise.EMadbatah.BLL.EPServiceClient.IEPService>, TayaIT.Enterprise.EMadbatah.BLL.EPServiceClient.IEPService {
        
        public EPServiceClient() {
        }
        
        public EPServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EPServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EPServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EPServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Data.DataSet GetEParlimentSessionDetails(long sessionID) {
            return base.Channel.GetEParlimentSessionDetails(sessionID);
        }
        
        public System.Data.DataSet UpdateEParlimentSessionDetails(long sessionID) {
            return base.Channel.UpdateEParlimentSessionDetails(sessionID);
        }
        
        public bool IngestContentsForFinalApprove(long sessionID) {
            return base.Channel.IngestContentsForFinalApprove(sessionID);
        }
        
        public int CheckHealth(int id) {
            return base.Channel.CheckHealth(id);
        }
    }
}
