//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TayaIT.Enterprise.EMadbatah.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EmadbatahRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmadbatahRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TayaIT.Enterprise.EMadbatah.Localization.EmadbatahRes", typeof(EmadbatahRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأول.
        /// </summary>
        internal static string str1 {
            get {
                return ResourceManager.GetString("str1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العاشر.
        /// </summary>
        internal static string str10 {
            get {
                return ResourceManager.GetString("str10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحادي عشر.
        /// </summary>
        internal static string str11 {
            get {
                return ResourceManager.GetString("str11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثاني عشر.
        /// </summary>
        internal static string str12 {
            get {
                return ResourceManager.GetString("str12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثالث عشر.
        /// </summary>
        internal static string str13 {
            get {
                return ResourceManager.GetString("str13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابع عشر.
        /// </summary>
        internal static string str14 {
            get {
                return ResourceManager.GetString("str14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخامس عشر.
        /// </summary>
        internal static string str15 {
            get {
                return ResourceManager.GetString("str15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السادس عشر.
        /// </summary>
        internal static string str16 {
            get {
                return ResourceManager.GetString("str16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابع عشر.
        /// </summary>
        internal static string str17 {
            get {
                return ResourceManager.GetString("str17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثامن عشر.
        /// </summary>
        internal static string str18 {
            get {
                return ResourceManager.GetString("str18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاسع عشر.
        /// </summary>
        internal static string str19 {
            get {
                return ResourceManager.GetString("str19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثاني.
        /// </summary>
        internal static string str2 {
            get {
                return ResourceManager.GetString("str2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العشرون.
        /// </summary>
        internal static string str20 {
            get {
                return ResourceManager.GetString("str20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحادي والعشرون.
        /// </summary>
        internal static string str21 {
            get {
                return ResourceManager.GetString("str21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثاني والعشرون.
        /// </summary>
        internal static string str22 {
            get {
                return ResourceManager.GetString("str22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثالث والعشرون.
        /// </summary>
        internal static string str23 {
            get {
                return ResourceManager.GetString("str23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابع والعشرون.
        /// </summary>
        internal static string str24 {
            get {
                return ResourceManager.GetString("str24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخامس والعشرون.
        /// </summary>
        internal static string str25 {
            get {
                return ResourceManager.GetString("str25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السادس والعشرون.
        /// </summary>
        internal static string str26 {
            get {
                return ResourceManager.GetString("str26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابع والعشرون.
        /// </summary>
        internal static string str27 {
            get {
                return ResourceManager.GetString("str27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثامن والعشرون.
        /// </summary>
        internal static string str28 {
            get {
                return ResourceManager.GetString("str28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاسع والعشرون.
        /// </summary>
        internal static string str29 {
            get {
                return ResourceManager.GetString("str29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثالث.
        /// </summary>
        internal static string str3 {
            get {
                return ResourceManager.GetString("str3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثلاثون.
        /// </summary>
        internal static string str30 {
            get {
                return ResourceManager.GetString("str30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحادي والثلاثون.
        /// </summary>
        internal static string str31 {
            get {
                return ResourceManager.GetString("str31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثاني والثلاثون.
        /// </summary>
        internal static string str32 {
            get {
                return ResourceManager.GetString("str32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثالث والثلاثون.
        /// </summary>
        internal static string str33 {
            get {
                return ResourceManager.GetString("str33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابع والثلاثون.
        /// </summary>
        internal static string str34 {
            get {
                return ResourceManager.GetString("str34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخامس والثلاثون.
        /// </summary>
        internal static string str35 {
            get {
                return ResourceManager.GetString("str35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السادس والثلاثون.
        /// </summary>
        internal static string str36 {
            get {
                return ResourceManager.GetString("str36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابع والثلاثون.
        /// </summary>
        internal static string str37 {
            get {
                return ResourceManager.GetString("str37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثامن والثلاثون.
        /// </summary>
        internal static string str38 {
            get {
                return ResourceManager.GetString("str38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاسع والثلاثون.
        /// </summary>
        internal static string str39 {
            get {
                return ResourceManager.GetString("str39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابع.
        /// </summary>
        internal static string str4 {
            get {
                return ResourceManager.GetString("str4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاربعون.
        /// </summary>
        internal static string str40 {
            get {
                return ResourceManager.GetString("str40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخامس.
        /// </summary>
        internal static string str5 {
            get {
                return ResourceManager.GetString("str5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السادس.
        /// </summary>
        internal static string str6 {
            get {
                return ResourceManager.GetString("str6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابع.
        /// </summary>
        internal static string str7 {
            get {
                return ResourceManager.GetString("str7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثامن.
        /// </summary>
        internal static string str8 {
            get {
                return ResourceManager.GetString("str8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاسع.
        /// </summary>
        internal static string str9 {
            get {
                return ResourceManager.GetString("str9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تطبيق المضبطة الإلكترونية.
        /// </summary>
        internal static string strAppName {
            get {
                return ResourceManager.GetString("strAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجمعة.
        /// </summary>
        internal static string strDayFriday {
            get {
                return ResourceManager.GetString("strDayFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإثنين.
        /// </summary>
        internal static string strDayMonday {
            get {
                return ResourceManager.GetString("strDayMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السبت.
        /// </summary>
        internal static string strDaySaturday {
            get {
                return ResourceManager.GetString("strDaySaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحد.
        /// </summary>
        internal static string strDaySunday {
            get {
                return ResourceManager.GetString("strDaySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخميس.
        /// </summary>
        internal static string strDayThursday {
            get {
                return ResourceManager.GetString("strDayThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثلاثاء.
        /// </summary>
        internal static string strDayTuesday {
            get {
                return ResourceManager.GetString("strDayTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأربعاء.
        /// </summary>
        internal static string strDayWednesday {
            get {
                return ResourceManager.GetString("strDayWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر.
        /// </summary>
        internal static string strDDLSelect {
            get {
                return ResourceManager.GetString("strDDLSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية -- تمت الموافقة على الجلسة.
        /// </summary>
        internal static string strEmailSubjApproveSession {
            get {
                return ResourceManager.GetString("strEmailSubjApproveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية --  تخصيص مصحح لملف صوتي.
        /// </summary>
        internal static string strEmailSubjAssignSessionFile {
            get {
                return ResourceManager.GetString("strEmailSubjAssignSessionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية -- تخصيص مراجع ملف.
        /// </summary>
        internal static string strEmailSubjAssignSessionFileReviewer {
            get {
                return ResourceManager.GetString("strEmailSubjAssignSessionFileReviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية --  تخصيص مراجع للمضبطة.
        /// </summary>
        internal static string strEmailSubjAssignSessionRev {
            get {
                return ResourceManager.GetString("strEmailSubjAssignSessionRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية -- تغيير الصلاحيات الخاصة بكم.
        /// </summary>
        internal static string strEmailSubjChangeUserRole {
            get {
                return ResourceManager.GetString("strEmailSubjChangeUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية -- إيقاف الحساب الخاص بكم.
        /// </summary>
        internal static string strEmailSubjDeActivateUser {
            get {
                return ResourceManager.GetString("strEmailSubjDeActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية -- إزالة الحساب الخاص بكم من التطبيق.
        /// </summary>
        internal static string strEmailSubjDeleteUser {
            get {
                return ResourceManager.GetString("strEmailSubjDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية -- تم التصديق على الجلسة.
        /// </summary>
        internal static string strEmailSubjFinalApproveSession {
            get {
                return ResourceManager.GetString("strEmailSubjFinalApproveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية --  لم يتم التصديق بنجاح.
        /// </summary>
        internal static string strEmailSubjFinalApproveSessionFail {
            get {
                return ResourceManager.GetString("strEmailSubjFinalApproveSessionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية -- تم انشاء ملف المضبطه.
        /// </summary>
        internal static string strEmailSubjMadbatahFileCreated {
            get {
                return ResourceManager.GetString("strEmailSubjMadbatahFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية -- فشل انشاء ملفات المضبطه.
        /// </summary>
        internal static string strEmailSubjMadbatahFilesCreationFailed {
            get {
                return ResourceManager.GetString("strEmailSubjMadbatahFilesCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية --  تم انشاء ملف الورد الخاص بالمضبطة.
        /// </summary>
        internal static string strEmailSubjNewMadbatahWordFileCreated {
            get {
                return ResourceManager.GetString("strEmailSubjNewMadbatahWordFileCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية -- مستخدم جديد.
        /// </summary>
        internal static string strEmailSubjNewUser {
            get {
                return ResourceManager.GetString("strEmailSubjNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية --  إعادة تخصيص ملف صوتي.
        /// </summary>
        internal static string strEmailSubjReAssignSessionFile {
            get {
                return ResourceManager.GetString("strEmailSubjReAssignSessionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية -- إعادة  تخصيص مراجع ملف.
        /// </summary>
        internal static string strEmailSubjReAssignSessionFileReviewer {
            get {
                return ResourceManager.GetString("strEmailSubjReAssignSessionFileReviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية -- إعادة تخصيص مراجع.
        /// </summary>
        internal static string strEmailSubjReAssignSessionRev {
            get {
                return ResourceManager.GetString("strEmailSubjReAssignSessionRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية --  مضبطة الجلسة مكتملة.
        /// </summary>
        internal static string strEmailSubjSessionMarkedAsComplete {
            get {
                return ResourceManager.GetString("strEmailSubjSessionMarkedAsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية --  فك القفل من ملف.
        /// </summary>
        internal static string strEmailSubjUnlockSessionFile {
            get {
                return ResourceManager.GetString("strEmailSubjUnlockSessionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية --  فك القفل من مراجع ملف.
        /// </summary>
        internal static string strEmailSubjUnlockSessionFileReviewer {
            get {
                return ResourceManager.GetString("strEmailSubjUnlockSessionFileReviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المضبطة الإلكترونية --  فك القفل من مراجع .
        /// </summary>
        internal static string strEmailSubjUnlockSessionRev {
            get {
                return ResourceManager.GetString("strEmailSubjUnlockSessionRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد ملف يمكنك مراجعته .
        /// </summary>
        internal static string strFileCanBeTaken {
            get {
                return ResourceManager.GetString("strFileCanBeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد ملفات يمكنك مراجعتها .
        /// </summary>
        internal static string strFilesCanBeTaken {
            get {
                return ResourceManager.GetString("strFilesCanBeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا... لقد حدت خطأ.
        /// </summary>
        internal static string strGeneric {
            get {
                return ResourceManager.GetString("strGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محرّم.
        /// </summary>
        internal static string strHijMonth1 {
            get {
                return ResourceManager.GetString("strHijMonth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شوال.
        /// </summary>
        internal static string strHijMonth10 {
            get {
                return ResourceManager.GetString("strHijMonth10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذو القعدة.
        /// </summary>
        internal static string strHijMonth11 {
            get {
                return ResourceManager.GetString("strHijMonth11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذو الحجة.
        /// </summary>
        internal static string strHijMonth12 {
            get {
                return ResourceManager.GetString("strHijMonth12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفر.
        /// </summary>
        internal static string strHijMonth2 {
            get {
                return ResourceManager.GetString("strHijMonth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ربيع الأول.
        /// </summary>
        internal static string strHijMonth3 {
            get {
                return ResourceManager.GetString("strHijMonth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ربيع الآخر.
        /// </summary>
        internal static string strHijMonth4 {
            get {
                return ResourceManager.GetString("strHijMonth4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمادى الأولى.
        /// </summary>
        internal static string strHijMonth5 {
            get {
                return ResourceManager.GetString("strHijMonth5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمادى الآخرة.
        /// </summary>
        internal static string strHijMonth6 {
            get {
                return ResourceManager.GetString("strHijMonth6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجب.
        /// </summary>
        internal static string strHijMonth7 {
            get {
                return ResourceManager.GetString("strHijMonth7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعبان.
        /// </summary>
        internal static string strHijMonth8 {
            get {
                return ResourceManager.GetString("strHijMonth8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمضان.
        /// </summary>
        internal static string strHijMonth9 {
            get {
                return ResourceManager.GetString("strHijMonth9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الواحدة.
        /// </summary>
        internal static string strHour1 {
            get {
                return ResourceManager.GetString("strHour1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العاشرة.
        /// </summary>
        internal static string strHour10 {
            get {
                return ResourceManager.GetString("strHour10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحادية عشر.
        /// </summary>
        internal static string strHour11 {
            get {
                return ResourceManager.GetString("strHour11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثانية عشر.
        /// </summary>
        internal static string strHour12 {
            get {
                return ResourceManager.GetString("strHour12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثانية.
        /// </summary>
        internal static string strHour2 {
            get {
                return ResourceManager.GetString("strHour2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثالثة.
        /// </summary>
        internal static string strHour3 {
            get {
                return ResourceManager.GetString("strHour3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابعة.
        /// </summary>
        internal static string strHour4 {
            get {
                return ResourceManager.GetString("strHour4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخامسة.
        /// </summary>
        internal static string strHour5 {
            get {
                return ResourceManager.GetString("strHour5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السادسة.
        /// </summary>
        internal static string strHour6 {
            get {
                return ResourceManager.GetString("strHour6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السابعة.
        /// </summary>
        internal static string strHour7 {
            get {
                return ResourceManager.GetString("strHour7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثامنة.
        /// </summary>
        internal static string strHour8 {
            get {
                return ResourceManager.GetString("strHour8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاسعة.
        /// </summary>
        internal static string strHour9 {
            get {
                return ResourceManager.GetString("strHour9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انت لست عضوا في الأكتيف ديريكتوري الخاص بالمجلس .. غير مسموح لك بالدخول إلى هذه الصفحة .. قم بالرجوع إلى مدير النظام.
        /// </summary>
        internal static string strInvalidDomain {
            get {
                return ResourceManager.GetString("strInvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افتتاح الجلسة , و كلمة معالي رئيس المجلس.
        /// </summary>
        internal static string strMadbatahStartAgendaItem {
            get {
                return ResourceManager.GetString("strMadbatahStartAgendaItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يناير.
        /// </summary>
        internal static string strMonth1 {
            get {
                return ResourceManager.GetString("strMonth1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أكتوبر.
        /// </summary>
        internal static string strMonth10 {
            get {
                return ResourceManager.GetString("strMonth10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوفمبر.
        /// </summary>
        internal static string strMonth11 {
            get {
                return ResourceManager.GetString("strMonth11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ديسمبر.
        /// </summary>
        internal static string strMonth12 {
            get {
                return ResourceManager.GetString("strMonth12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فبراير.
        /// </summary>
        internal static string strMonth2 {
            get {
                return ResourceManager.GetString("strMonth2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مارس.
        /// </summary>
        internal static string strMonth3 {
            get {
                return ResourceManager.GetString("strMonth3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابريل.
        /// </summary>
        internal static string strMonth4 {
            get {
                return ResourceManager.GetString("strMonth4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مايو.
        /// </summary>
        internal static string strMonth5 {
            get {
                return ResourceManager.GetString("strMonth5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يونيو.
        /// </summary>
        internal static string strMonth6 {
            get {
                return ResourceManager.GetString("strMonth6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوليو.
        /// </summary>
        internal static string strMonth7 {
            get {
                return ResourceManager.GetString("strMonth7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أغسطس.
        /// </summary>
        internal static string strMonth8 {
            get {
                return ResourceManager.GetString("strMonth8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبتمبر.
        /// </summary>
        internal static string strMonth9 {
            get {
                return ResourceManager.GetString("strMonth9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد حدث خطأ في خدمة البرلمان الإلكتروني .. من فضلك أعد المحاولة.
        /// </summary>
        internal static string strMsgErrorEPService {
            get {
                return ResourceManager.GetString("strMsgErrorEPService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يستطع النظام الوصول لمجلد الجلسة .. لا تستطيع بدء مضبطة الجلسة قبل وجود المجلد.
        /// </summary>
        internal static string strMsgWarnNoVecsysFolder {
            get {
                return ResourceManager.GetString("strMsgWarnNoVecsysFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك عمل مراجعة لأي ملف في المضبطة .. جميع الملفات مخصصة لمراجعين آخرين.
        /// </summary>
        internal static string strNoFreeFilesFound {
            get {
                return ResourceManager.GetString("strNoFreeFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن فتح هذه الصفحه بدون مدخلات.
        /// </summary>
        internal static string strNoQueryStr {
            get {
                return ResourceManager.GetString("strNoQueryStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا...لا يوجد اي جلسات في النظام حتي الان.
        /// </summary>
        internal static string strNoSessionsExistWarn {
            get {
                return ResourceManager.GetString("strNoSessionsExistWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدير النظام.
        /// </summary>
        internal static string strRole1 {
            get {
                return ResourceManager.GetString("strRole1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصحح.
        /// </summary>
        internal static string strRole2 {
            get {
                return ResourceManager.GetString("strRole2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجع.
        /// </summary>
        internal static string strRole3 {
            get {
                return ResourceManager.GetString("strRole3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجع و مصحح.
        /// </summary>
        internal static string strRole4 {
            get {
                return ResourceManager.GetString("strRole4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجع ملف.
        /// </summary>
        internal static string strRole5 {
            get {
                return ResourceManager.GetString("strRole5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق عليه.
        /// </summary>
        internal static string strSessionFileStatusApproved {
            get {
                return ResourceManager.GetString("strSessionFileStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم.
        /// </summary>
        internal static string strSessionFileStatusCompleted {
            get {
                return ResourceManager.GetString("strSessionFileStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد التعديل.
        /// </summary>
        internal static string strSessionFileStatusInProgress {
            get {
                return ResourceManager.GetString("strSessionFileStatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        internal static string strSessionFileStatusNew {
            get {
                return ResourceManager.GetString("strSessionFileStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق عليه.
        /// </summary>
        internal static string strSessionStatusApproved {
            get {
                return ResourceManager.GetString("strSessionStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكتمل.
        /// </summary>
        internal static string strSessionStatusCompleted {
            get {
                return ResourceManager.GetString("strSessionStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصدق.
        /// </summary>
        internal static string strSessionStatusFinalApproved {
            get {
                return ResourceManager.GetString("strSessionStatusFinalApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد الإنشاء.
        /// </summary>
        internal static string strSessionStatusInProgress {
            get {
                return ResourceManager.GetString("strSessionStatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        internal static string strSessionStatusNew {
            get {
                return ResourceManager.GetString("strSessionStatusNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا... لم يتم بدأ العمل في المضبطه بعد.
        /// </summary>
        internal static string strSessionStillWithNoWork {
            get {
                return ResourceManager.GetString("strSessionStillWithNoWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لتغيير المستخدم الحالي قم بالضغط على رابط الدخول بحساب مختلف و للخروج نهائياً يجب اختيار خروج و إغلاق نافذة المتصفح.
        /// </summary>
        internal static string strSignInAsDifferentUserWarning {
            get {
                return ResourceManager.GetString("strSignInAsDifferentUserWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لإتمام عملية الخروج بشكل صحيح يجب غلق نافذة المتصفح.
        /// </summary>
        internal static string strSignOutWarning {
            get {
                return ResourceManager.GetString("strSignOutWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صباحا.
        /// </summary>
        internal static string strTimeAM {
            get {
                return ResourceManager.GetString("strTimeAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساءا.
        /// </summary>
        internal static string strTimePM {
            get {
                return ResourceManager.GetString("strTimePM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا... غير مسموح لك بالدخول إلى هذه الصفحة .. قم بالرجوع إلى مدير النظام.
        /// </summary>
        internal static string strUnauthorized {
            get {
                return ResourceManager.GetString("strUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفوا... غير مسموح لك بالدخول إلى هذه الصفحة .. لم يتم تفعيل حسابك بعد .. قم بالرجوع إلى مدير النظام.
        /// </summary>
        internal static string strUserinActive {
            get {
                return ResourceManager.GetString("strUserinActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مسموح لك بعمل مراجعة لهذه الصفحة.
        /// </summary>
        internal static string strWrongReviewer {
            get {
                return ResourceManager.GetString("strWrongReviewer", resourceCulture);
            }
        }
    }
}
